### ISSUE TITLE
main.py: error: unrecognized arguments: --temperature=0.1 --strength=0.5

### ISSUE THREAD

**Issue by chho-work** [dmolony3/SimCLR#2]
Hi,

When running the command: 
"!python main.py --task=pretrain --cifar10=True --batch_size=256 --num_epochs=1000 --temperature=0.1 --strength=0.5 --learning_rate=1.0" 

on Colab GPU, I received the following message.

********************************************************************************************************************************************

usage: main.py [-h] [--task TASK] [--model MODEL]
               [--imagenet_path IMAGENET_PATH] [--input_size INPUT_SIZE]
               [--crop_size CROP_SIZE] [--batch_size BATCH_SIZE]
               [--weight_decay WEIGHT_DECAY] [--learning_rate LEARNING_RATE]
               [--train_file_path TRAIN_FILE_PATH]
               [--val_file_path VAL_FILE_PATH]
               [--pretrain_save_path PRETRAIN_SAVE_PATH]
               [--finetune_save_path FINETUNE_SAVE_PATH] [--cifar10 CIFAR10]
               [--num_classes NUM_CLASSES] [--num_epochs NUM_EPOCHS]
               [--freeze] [--blur] [--no-blur] [--rotate] [--jitter]
               [--no-jitter] [--crop] [--no-crop] [--flip] [--no-flip]
               [--noise] [--no-noise] [--colordrop] [--no-colordrop]
main.py: error: unrecognized arguments: --temperature=0.1 --strength=0.5

****************************************************************************************************************************************
Pls kindly help!  Many thanks!

**Comment by dmolony3** [comment]
Looks like I never exposed the temperature and strength arguments to argparse. I've pushed changes to the code and this will now run without error.
